name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Hello
      run: echo Hello
    - name: cd unity
      run: cd unity
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: run
      run: ./unity_test 
